apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: "2024-12-03T11:35:58Z"
  generation: 1
  name: cartfurnish-tls
  namespace: default
  ownerReferences:
  - apiVersion: networking.k8s.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Ingress
    name: my-ingress
    uid: d490eedf-5319-4b18-9e0c-876e37d134bf
  resourceVersion: "208441"
  uid: 3e856226-1c78-497a-accd-0dc4dae936df
spec:
  dnsNames:
  - api.homeport.online
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cartfurnish-tls
  usages:
  - digital signature
  - key encipherment
status:
  conditions:
  - lastTransitionTime: "2024-12-03T11:36:23Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2025-03-03T10:37:50Z"
  notBefore: "2024-12-03T10:37:51Z"
  renewalTime: "2025-02-01T10:37:50Z"
  revision: 1
