version: '3.8'

services:
  user:
    build:
      context: ./user
    ports:
      - "5001:5001"
    networks:
      - app-network

  admin:
    build:
      context: ./admin
    ports:
      - "5002:5002"
    networks:
      - app-network

  property:
    build:
      context: ./property
    ports:
      - "5003:5003"
    networks:
      - app-network

  booking:
    build:
      context: ./booking
    ports:
      - "5004:5004"
    networks:
      - app-network

  chat:
    build:
      context: ./chat
    ports:
      - "3000:3000"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest  
    networks:
      - app-network

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    networks:
      - app-network    

networks:
  app-network:
    driver: bridge