const validationRules = {
    address: { required: true, message: "Address is required." },
    areBillsIncluded: { required: false },
    availableFrom: { required: true, message: "Available from date is required." },
    balconies: { required: true, type: 'number', min: 0, message: "Balconies must be 0 or more." },
    bathrooms: { required: true, type: 'number', min: 0, message: "Bathrooms must be 0 or more." },
    bedrooms: { required: true, type: 'number', min: 0, message: "Bedrooms must be 0 or more." },
    city: { required: true, message: "City is required." },
    description: { required: true, message: "Description is required." },
    directionTips: { required: false },
    electronics: { required: false },
    eligibility: { required: false },
    facing: { required: false },
    furnisherType: { required: false },
    hasWell: { required: false },
    isNegotiable: { required: false },
    latitude: { required: true, type: 'number', message: "Latitude is required." },
    longitude: { required: true, type: 'number', message: "Longitude is required." },
    lookingFor: { required: true, message: "You must specify if you're looking for rent or sale." },
    mediaFiles: { required: false, message: "You must upload at least 3 media files." },
    noOfBikes: { required: false, type: 'number', min: 0 },
    noOfCars: { required: false, type: 'number', min: 0 },
    noOfScooters: { required: false, type: 'number', min: 0 },
    openings: { required: false, type: 'number', min: 0 },
    otherRooms: { required: false },
    propertyAdvantages: { required: false },
    propertyAge: { required: false },
    propertyCondition: { required: false },
    propertyFeatures: { required: false },
    propertyType: { required: true, message: "Property type is required." },
    totalArea: { required: true, type: 'number', min: 0, message: "Total area is required." },
    totalFloors: { required: true, type: 'number', min: 0, message: "Total floors are required." }
};

export default validationRules;
