apiVersion: v1
kind: ConfigMap
metadata:
  name: config-booking
data:
  MONGO_URL: "mongodb+srv://mzayed9745:mohammadzayed9745@projectcluster.dozic4b.mongodb.net/booking?retryWrites=true&w=majority&appName=ProjectCluster"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  CORS_ORIGIN: "https://homeport.online"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: zayed17/realestate-booking:latest
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: config-booking

---

apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP
