apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: zayed17/realestate-chat:latest
          ports:
            - containerPort: 3000
         
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP