apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 rabbitmq 5672; do echo "Waiting for RabbitMQ..."; sleep 5; done; echo "RabbitMQ is up and running!"']
      containers:
        - name: user-service
          image: zayed17/realestate-user:latest
          ports:
            - containerPort: 5001
         
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP